name: Compile
on: [push]
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.0.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Using Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Dependencies
        run: npm install

      - name: Compile project
        run: |
          npx hardhat compile
